### PR TITLE
Cut by photon number

### PR DESCRIPTION
**Pull request by nwittler**
This introduces cutting the simulation space by excitation number.

## Use
`Model(..., max_excitations=3)` to limit the excitation number. Default is 0, with unchanged behavior.

## How
After constructing the product annihilation operators, we count the number of excitations and project the annihilators accordingly. For the purpose of fidelities, the propagators are padded with the same operator back to the full product Hilbert space size. This can be done more elegantly.

### CODE REVIEW

**Comment by GlaserN** [comment]
A problem in cutting the annihilation operators is that the resulting hamiltonians are not necessarily hermitian anymore. Which is especially problematic for the dressing. I would have thought to reduce the dimensions only during the propagation, however this still leaves a relevant memory overhead.

**Comment by shaimach** [comment]
To cut down Hermitian and unitary matrices "safely", diagonalize, then cut,
then reconstruct

**Comment by nwittler** [comment]
As discussed, the cutting and its inverse now happen as part of the propagation method.

**Comment by nwittler** [comment]
Good point. I wasn't sure how to deal with the partial propagators since that introduces a lot more matrix multiplications. At some point let's test what the performance impact of the transformation between Hilbert spaces is.

**Pull request merged**
