### PR TITLE
Revert "Arbitrary basis"

### PR DESCRIPTION
**Pull request by fedroy**
Reverts q-optimize/c3#220 to verify correct functioning of test notebook

### CODE REVIEW

**Comment by lazyoracle** [comment]
Notebooks are fine. The issue is not with this PR. The out of bounds error has existed for some time now. We can investigate it but we hopefully do not need to revert this PR. Reverting will unnecessarily dirty the git history.

**Comment by MaxNaeg** [comment]
We thought there was also a second issue with the code, but it's actually fine. Let's cancel this pull request and not revert.

**Comment by lazyoracle** [comment]
Yeah, in general, since we have a separate stable `master` and new Pull Requests only get merged into the unstable `dev`, it's fine to have buggy and WIP features getting merged. The earlier its merged, the better. We can always fix broken or semi-working things later on by making another PR that introduces the fix.

**Comment by fedroy** [comment]
great, then I'm closing this PR

**Pull request closed without merging**
