### PR TITLE
Three wave mixing element, third order nonlinear hamiltonian and tests

### PR DESCRIPTION
**Pull request by Radioactive-Waste**
Added the recommended changes, including a test file and many more comments.

### CODE REVIEW

**Review by lazyoracle — CHANGES_REQUESTED** [review]
Can you rename `test/three_wave_mixer_test.py` to `test/test_three_wave_mixer.py`?

**Comment by Radioactive-Waste** [comment]
Done

**Comment by lazyoracle** [comment]
Thanks for being patient Gerhard. Still a few issues remain to be resolved. As you might have seen, this PR unlike the previous ones that you opened (which btw you didn't need to close, because you can make changes to your branch after opening the PR), there were no checks automatically run on your code. Ideally you should be trying to merge code from a relevant branch in your repository (like you were doing previously, eg, `patch-1`) into `dev` in this repo, unlike currently the merge from `master` in your repo. 
So, I ran the tests locally to check if everything is fine and I get the following error when running the tests.

<details>
<summary> Click to expand error </summary>

```
pytest -v test/ --cov=c3/                                                                                                                         (c3-qiskit)  11-01 Mon 09:19
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /home/anurag/miniconda3/envs/c3-qiskit/bin/python
cachedir: .pytest_cache
rootdir: /home/anurag/Dev-Related/test-pr/c3, configfile: pytest.ini
plugins: cov-2.10.1
collected 49 items / 1 error / 48 selected                                                                                                                                                   

=========================================================================================== ERRORS ===========================================================================================
_______________________________________________________________________ ERROR collecting test/test_three_wave_mixer.py _______________________________________________________________________
test/test_three_wave_mixer.py:63: in <module>
    [S1],  # Individual, self-contained components
E   NameError: name 'S1' is not defined
====================================================================================== warnings summary ======================================================================================
c3/libraries/hamiltonians.py:54
  /home/anurag/Dev-Related/test-pr/c3/c3/libraries/hamiltonians.py:54: DeprecationWarning: invalid escape sequence \d
    """

-- Docs: https://docs.pytest.org/en/stable/warnings.html

----------- coverage: platform linux, python 3.8.5-final-0 -----------
Name                           Stmts   Miss  Cover
--------------------------------------------------
c3/__init__.py                     1      0   100%
c3/c3objs.py                      89     26    71%
c3/experiment.py                 188    115    39%
c3/generator/__init__.py           0      0   100%
c3/generator/devices.py          283    103    64%
c3/generator/generator.py         56      8    86%
c3/libraries/__init__.py           0      0   100%
c3/libraries/algorithms.py       253    218    14%
c3/libraries/constants.py          4      0   100%
c3/libraries/envelopes.py        109     65    40%
c3/libraries/estimators.py       102    102     0%
c3/libraries/fidelities.py       357    302    15%
c3/libraries/hamiltonians.py      45     12    73%
c3/libraries/sampling.py          46     46     0%
c3/main.py                       102    102     0%
c3/optimizers/__init__.py          0      0   100%
c3/optimizers/c1.py               71     50    30%
c3/optimizers/c2.py               66     66     0%
c3/optimizers/c3.py              212    212     0%
c3/optimizers/optimizer.py       114     80    30%
c3/optimizers/sensitivity.py     132    132     0%
c3/parametermap.py               154     74    52%
c3/signal/__init__.py              0      0   100%
c3/signal/gates.py                33      7    79%
c3/signal/pulse.py                53     15    72%
c3/system/__init__.py              0      0   100%
c3/system/chip.py                210     92    56%
c3/system/model.py               211     64    70%
c3/system/tasks.py                53     29    45%
c3/utils/__init__.py               0      0   100%
c3/utils/log_reader.py            41     41     0%
c3/utils/parsers.py              243    243     0%
c3/utils/qt_utils.py             341    259    24%
c3/utils/tf_utils.py             233    174    25%
c3/utils/utils.py                 58     50    14%
--------------------------------------------------
TOTAL                           3860   2687    30%

================================================================================== short test summary info ===================================================================================
ERROR test/test_three_wave_mixer.py - NameError: name 'S1' is not defined
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================================ 1 warning, 1 error in 5.71s =================================================================================
```

</details>

If you notice towards the top of that test report, it mentions the errors in your test suite `test_three_wave_mixer.py`, i.e., `name 'S1' is not defined` and also gives you a warning about an `invalid escape sequence \d`

I am sorry that this has required multiple rounds of revisions from us, but our code is changing frequently these days and without good tests (which you have already written, thanks for that), we won't be able to ensure that someone else doesn't mess up the work you did.

**Comment by Radioactive-Waste** [comment]
Thank you for your comment, when I run my pytest code manually on my computer it now seems to work without errors. However, with my c3 version (0.2dev) I do not have to multiply by 2 Pi in the frequency assertion test. Otherwise, it runs fine.

**Comment by lazyoracle** [comment]
So the recommended steps for running the tests locally is as follows. This is intended to ensure that you are running the tests against the latest version of your local code and there are no conflicts with other versions of the package installed locally.

* Create a new `conda` or `virtualenv`. Check instructions for [installing](https://docs.conda.io/en/latest/miniconda.html#linux-installers) and [using](https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html) Conda OR for [Virtual Environment](https://realpython.com/python-virtual-environments-a-primer/#using-virtual-environments)
* Clone and navigate into the repo, eg, in this case:
  ```bash
  git clone https://github.com/Radioactive-Waste/c3
  cd c3/
  ```
* Create an editable install of the latest version of your `c3-toolset` with `pip install -e .` from the root of your local `c3/` repo
* Install `pytest` and `coverage` with `pip install pytest-cov`
* Run the tests locally with `pytest -v test/ --cov=c3/` from the root of the repo

When I follow the above steps, I get the following error:
```python
========================================== test session starts ==========================================
platform linux -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /home/anurag/miniconda3/envs/c3po/bin/python
cachedir: .pytest_cache
rootdir: /home/anurag/Dev-Related/test-pr/c3, configfile: pytest.ini
plugins: cov-2.10.1
collected 49 items / 1 error / 48 selected                                                              

================================================ ERRORS =================================================
____________________________ ERROR collecting test/test_three_wave_mixer.py _____________________________
test/test_three_wave_mixer.py:59: in <module>
    init_temp=Quantity(value=init_temp, min=-0.001, max=0.22, unit="K")
E   TypeError: __init__() got an unexpected keyword argument 'min'
```

**Comment by Radioactive-Waste** [comment]
Thank you, the error was from the older version where the minimum value had the key min instead of min_val, I changed that now (same for max)

**Comment by lazyoracle** [comment]
You probably want to use better commit messages in case you ever want to look back on how you debugged this 😅

**Comment by Radioactive-Waste** [comment]
Probably, but they were obvious typos and minor mistakes, I get the following test results:
c3_pytest_pass

**Comment by lazyoracle** [comment]
Yep, just ran the tests locally and everything looks fine. I will re-review and approve. Have requested review from @fedroy and will keep this on standby until we merge his branch on `iswap`. Don't think there should be any more requests for further changes on this PR. Thanks for the your first contribution to `c3` 🍻

**Review by lazyoracle — DISMISSED** [review]
LGTM!

**Comment by Radioactive-Waste** [comment]
🍻

**Comment by shaimach** [comment]
I may be way off, but:

1. We need some references (in the scientific sense) in SNAIL and three_wave_mixing (and generally whenever non-trivial physics or math is used).
2. SNAIL.get_Lindbladian() seems rather generic, and not SNAIL specific. So we should only have one implementation for the thermalization and dephasing Lindblads.

**Comment by Radioactive-Waste** [comment]
I added the review paper where the SNAIL is first introduced, explained and derived. 
The Lindbladian is generic, since it is a generic one for the SNAIL.

**Comment by shaimach** [comment]
Is the SNAIL Lindblandian different than the standard one? 
(I briefly looked at the code and it seems the same)

**Comment by Radioactive-Waste** [comment]
No, it is the same one as for the Qubit, since the emission and capture of excitations is dependant on the external coupling to the element and we can treat the SNAIL like a Qubit in that regard (as far as I know of course).

**Comment by shaimach** [comment]
If it's the same, then there should be a single piece of code implementing it.

**Comment by Radioactive-Waste** [comment]
It has the exact same code as the Qubit class for the Lindbladian.

**Comment by lazyoracle** [comment]
To rephrase @shaimach's review , we want *code reuse*, i.e, a functionality implemented in one section of the code base should not be reimplemented elsewhere. Reimplementation includes copying the code over from another section of the codebase to a local function in your feature. Instead the same code should be used by importing the module or inheriting the required class.

**Comment by Radioactive-Waste** [comment]
I see, it should be changed now.

**Comment by Radioactive-Waste** [comment]
Should I change something else about the code?

**Comment by fedroy** [comment]
I still have to give it a look. Will do it today

**Comment by lazyoracle** [comment]
@shaimach @fedroy Can you please review and either approve or request more changes?
@Radioactive-Waste Once approved by them, we will go ahead and merge it.

**Review by fedroy — COMMENTED** [review]
the code seems to check out, is that SNAIL hamiltonian neglecting triple excitation terms (aaa and a*a*a*) or do they not appear in the derivation?

**Comment by Radioactive-Waste** [comment]
Yes, the Snail is neglecting them, since the three wave mixing comes from a taylored potential around the flux minimum, so these terms are neglected as far as I know.

**Comment by Radioactive-Waste** [comment]
The same is done in this Nakamura paper, where they have the same Hamiltonian :
https://arxiv.org/pdf/2005.02630.pdf

**Comment by lazyoracle** [comment]
@fedroy @shaimach If you are happy with the changes, can you add your review and approve the changes? I think we can go ahead with merging it today if there aren't other issues to be addressed.

[Approving PR Reviews](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/approving-a-pull-request-with-required-reviews)

**Comment by shaimach** [comment]
I'm afraid I will not have time before 8pm to look over this properly.

Another matter: If anybody new contributes to the code that is not employed
by FZJ, IBMZ, USAAR - we need an ok from the employer.

**Review by lazyoracle — APPROVED** [review]

**Review by nwittler — APPROVED** [review]
Looks good.

**Review by fedroy — APPROVED** [review]

**Pull request merged**
