### PR TITLE
Update format of the generator chain

### LINKED ISSUE #29: Store all signal and improve structuce of signal line
At the moment, most devices have a `self.signal` where the last signal that was produced gets stored.
For example:
https://github.com/q-optimize/c3/blob/815bf32a77040ebe6bb9ef0a91ba10f41432d1fb/c3/generator/devices.py#L926-L931

We should instead store all signals generated in the generator object by doing something like
```
signal_stack: List[tf.Variable] = []
for dev_id in self.chains[chan]:
    dev = self.devices[dev_id]
    ...
final_signal[chan] = copy.deepcopy(signal_stack.pop())
signal_stages[chan] = signal_stack
```
For this to work we would have to make sure that when taking elements from the signal stack they aren't popped.

However, this creates a problem: 
Imagine your generator stack has the following devices:
`LO, LO_noise, AWG, AWG_noise, Mixer`
where the `LO_noise` and `AWG_noise`  take 1 input and have 1 output.
Then the popping works because the mixer will find in the stack the noisy AWG output and the noisy LO output.
If we don't pop the stack when we get to the mixer would have the outputs:
`[LO, LO_noise, AWG, AWG_noise]`
And won't know that it needs to take the 2nd and 4th elements of the stack.

This leads to the point that we need to implement a more general (and more intuitive) signal generation chain that is a directed graph.
One way to do this would be when specifying the chain you specify the inputs.
What is currently:
```
chains={
        "TC":["lo", "lo_noise" , "awg", "dac", "resp", "mixer", "fluxbias"],
        "Q1":["lo", "awg", "dac", "resp", "mixer", "v2hz"],
    } 
```
could become:
```
chains={
        "TC": [("lo"), ("lo_noise","lo") , ("awg"), ("dac","awg"), ("resp","awg"), ("mixer","lo_noise","resp"), ("fluxbias", "mixer")]
        "Q1": [("lo") , ("awg"), ("dac","awg"), ("resp","awg"), ("mixer","lo","resp"), ("v2hz", "mixer")]
} 
```
where the first element of each tuple is the device that needs to make a signal and the others are the inputs.
This is to get closer to the point where we truly have a directed graph.
The tuple structure is just a suggestion but anything would do even:
```
chains={
        "TC": [
            {"device": "lo", "inputs" : []},
            {"device": "lo_noise", "inputs" : ["lo"]} ,
            ...,
            {"device": "mixer", "inputs" : ["awg", "lo"]},
            ...
        ]   
        "Q1": [{...}, ..., {...}]
} 
```

I'm aware this is a more annoying to setup but it does make more sense to someone that isn't familiar with the stack and how to make it work for new devices.

[thanks @GlaserN for the input]

### PR DESCRIPTION
**Pull request by alex-simm**
## What
Changes the form of the signal chain that the generator accepts into a dictionary. For each device, the dict specifies which devices are used as inputs, for example:
```
"d1": {
    "LO": [],
    "AWG": [],
    "DigitalToAnalog": ["AWG"],
    "Response": ["DigitalToAnalog"],
    "Mixer": ["LO", "Response"],
    "VoltsToHertz": ["Mixer"]
}
```
instead of
`"d1": ["LO", "AWG", "DigitalToAnalog", "Response", "Mixer", "VoltsToHertz"]`

Also, I added an optional callback to the generator which can be used for debugging during the signal generation.

## Why
Closes #29 

Previously, the order of the devices in the chain depended on the way the generator internally stored the signals on a stack. The dictionary can be created more intuitively and does not depend on the actual implementation of the generator.

## How
The generator brings the directed graph into topological order. Then it iterates through the devices, only storing the signals as long as they are needed. This implementation should be able to handle any signal chain, even if the output of one device is used as input for several others. In case of a cycle, it will raise an error.

## Remarks
I didn't test it with complicated signal chains, but some are covered by the unit tests.

## Checklist
- [ ] Tests - Added unit tests for new code, regression tests for bugs and updated the integration tests if required
- [x] Formatting & Linting - `black` and `flake8` have been used to ensure styling guidelines are met
- [x] Type Annotations - All new code has been type annotated in the function signatures using type hints
- [x] Docstrings - Docstrings have been provided for functions in the `numpydoc` style
- [ ] Documentation - The tutorial style documentation has been updated to explain changes & new features
- [x] Notebooks - Example notebooks have been updated to incorporate changes and new features
- [x] Changelog - A short note on this PR has been added to the Upcoming Release section

### CODE REVIEW

**Comment by alex-simm** [comment]
So far, the code is ready and should work. Some of the tests are failing because I used a package from python 3.9. Do we need that backwards compatibility?

**Comment by lazyoracle** [comment]
> 
> 
> So far, the code is ready and should work. Some of the tests are failing because I used a package from python 3.9. Do we need that backwards compatibility?

Yep, we only very recently moved to provide support for Python 3.9 and there is no plan to drop support for 3.6, 3.7 and 3.8 in the upcoming releases. So ideally we should not use any features that are Python 3.9 only

**Comment by lazyoracle** [comment]
A possible alternative to consider (which makes for a good choice despite being an external dependency) is [`networkx`](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.dag.topological_sort.html). It is widely used, stable, been around for a long time and is also used by other quantum programming toolchains (eg `qiskit` which also has their own re-implementation in rust [`retworkx`](https://github.com/Qiskit/retworkx). I would suggest we use `networkx` and drop support for Python 3.6 instead of dropping all previous versions in favour of the still pretty new Python 3.9 which many libraries don't fully support yet.

**Comment by shaimach** [comment]
If all we need is a topological sort of the signal generation DAG, then we
can implement it ourselves in < 1 day.

If we need more significantly more extensive graph algorithms, then using
an existing package makes sense.

**Comment by alex-simm** [comment]
I added a simple implementation of topological sorting. This should work without any dependence on python 3.9 now.

**Comment by lazyoracle** [comment]
Putting this on hold until #134 is fixed

**Review by nwittler — APPROVED** [review]
Good to go.

**Pull request merged**
