### PR TITLE
Compatibility fixes to prior versions

### PR DESCRIPTION
**Pull request by GlaserN**
Changes include:

- corrected behavior of flux tuning device
- streamline noise devices
- quantity object can be used as an argument for numpy functions, returning a np.array
- update the model if model parameters were changed
- more continous reordering of dressed states
- ...

This pull request also greatly improves perfomance,
- by using vectorized performance 
- providing a response function utilising fft instead of manual multiplication
- using tf.constants instead of tf.variables, where it is not explicitly necessary

### CODE REVIEW

**Comment by lazyoracle** [comment]
Hi @GlaserN, please check out the [CONTRIBUTING.md](https://github.com/q-optimize/c3/blob/master/CONTRIBUTING.md), on how to set up the `pre-commit` hooks. That should auto format and lint your commits and will pass the Code Formatting and Linting check that's currently failing.

**Review by lazyoracle — DISMISSED** [review]

**Comment by lazyoracle** [comment]
Does this address #26 ?

**Comment by GlaserN** [comment]
> Does this address #28 ?
No it does not. I guess a change there would need a proper discussion.

**Comment by fedroy** [comment]
@lazyoracle  after merging dev into the PR it fails the build (which was previously successful) and it seems to be some qiskit import. Could you give it a look?

**Comment by lazyoracle** [comment]
Fixed in #48  and merged to `dev`. Let me know if it still persists once you merge `dev` into `further_fixes`.

**Review by fedroy — APPROVED** [review]

**Pull request merged**
