### PR TITLE
Increase evaluation number in OptimalControl

### PR DESCRIPTION
**Pull request by alex-simm**
## What
Increases the evaluation index after each iteration. Currently, the number always stays at 1. I think this used to be in the code, but probably got lost somewhere.

## Why
Describe what motivated this Pull Request and why this was necessary. Use closing keywords to link to the relevant Issue. Ex. Closes #666

## How
Describe details of how you implemented the solution, outlining the major steps involved in adding this new feature or fixing this bug. Provide code-snippets if possible, showing example usage.

## Remarks
Add notes on possible known quirks/drawbacks of this solution. If this introduces an API-breaking change, please provide an explanation on why it is necessary to break API compatibility and how users should update their notebook/script workflows once this PR is merged.

## Checklist
Please include and complete the following checklist. Your Pull Request is (in most cases) not ready for review until the following have been completed. You can create a draft PR while you are still completing the checklist. Check the [Contribution Guidelines](https://github.com/q-optimize/c3/blob/dev/CONTRIBUTING.md) for more details. You can mark an item as complete with the `- [x]` prefix

- [x] Tests - Added unit tests for new code, regression tests for bugs and updated the integration tests if required
- [x] Formatting & Linting - `black` and `flake8` have been used to ensure styling guidelines are met
- [ ] Type Annotations - All new code has been type annotated in the function signatures using type hints
- [ ] Docstrings - Docstrings have been provided for functions in the `numpydoc` style
- [ ] Documentation - The tutorial style documentation has been updated to explain changes & new features
- [ ] Notebooks - Example notebooks have been updated to incorporate changes and new features
- [x] Changelog - A short note on this PR has been added to the Upcoming Release section

### CODE REVIEW

**Review by nwittler — CHANGES_REQUESTED** [review]
Better to change this in the superclass? Or does this not happen in calibration and model learning?

**Comment by nwittler** [comment]
Can you add a super simple test to check that the counter is increased correctly?

**Comment by alex-simm** [comment]
It does happen in both. I moved it to `fct_to_min` in the superclass now. Will have a look into tests.

**Comment by alex-simm** [comment]
The test is now added to test_two_qubits.py. I left the increment in the subclasses because it makes more sense to do it in `goal_run` than in `fct_to_min`.

**Review by nwittler — APPROVED** [review]
All good for now. The coverage complaint doesn't really make sense.

**Pull request merged**
