### PR TITLE
Adding state propagation using RK methods

### PR DESCRIPTION
**Pull request by Ashutosh-Mishra2**
## What
Adds state propagation using RK methods for calculating the dynamics. Also adds a method to just calculate the final state using the same method which might be faster for optimizations where only the final state is required.

## Why
Evolution of quantum system by calculating the superoperators can become computationally expensive very fast as the Hilbert space dimension increases. In these cases a propagation of states using RK methods can be faster.

## How
Added a new method "compute_states" in experiment class which calls an ode solver to solve the required ode (Schrodinger equation/ Von Neumann equation/ Lindblad master equation). Also there are various solvers , e.g. RK4, RK5 etc. and step functions that the user can specify.

## Checklist
Please include and complete the following checklist. Your Pull Request is (in most cases) not ready for review until the following have been completed. You can create a draft PR while you are still completing the checklist. Check the [Contribution Guidelines](https://github.com/q-optimize/c3/blob/dev/CONTRIBUTING.md) for more details. You can mark an item as complete with the `- [x]` prefix

- [x] Tests - Added unit tests for new code, regression tests for bugs and updated the integration tests if required
- [x] Formatting & Linting - `black` and `flake8` have been used to ensure styling guidelines are met
- [x] Type Annotations - All new code has been type annotated in the function signatures using type hints
- [ ] Docstrings - Docstrings have been provided for functions in the `numpydoc` style
- [x] Documentation - The tutorial style documentation has been updated to explain changes & new features
- [x] Notebooks - Example notebooks have been updated to incorporate changes and new features
- [ ] Changelog - A short note on this PR has been added to the Upcoming Release section

### CODE REVIEW

**Comment by lazyoracle** [comment]
@Ashutosh-Mishra2 Can you sign the CLA by clicking on the link the comment above?

**Comment by Ashutosh-Mishra2** [comment]
I have signed, it but it says the status is still pending. Does it usually take a few minutes?

**Comment by nwittler** [comment]
Some of the code climate things should be easy to fix, like not using CamelCase for some function. The complaints about copy-paste code in the examples we can live with from my perspective.

**Comment by lazyoracle** [comment]
Agree. Anything to do with examples can be left as is, but we should try to fix the other warnings in code climate. Can we get more test coverage because that seems to have dropped with the new changes in this PR?

**Comment by shaimach** [comment]
RK, as a general-purpose ODE solver, has a tendency not to preserve state norms.
Consider adding an assert to check it is still within epsilon of 1 (IMHO, a reasonable default would be 1e-6).

**Review by nwittler — APPROVED** [review]
Remaining code climate stuff is fine.

**Pull request merged**
