### PR TITLE
Add an example notebook for two-qubit entangling gates

### PR DESCRIPTION
**Pull request by alex-simm**
## What
In contrast to the existing two qubit example (`examples/two_qubits.ipynb`), this this an example that specifically optimises entangling gates.

## Why
~~Because the optimisation doesn't work. It usually converges to 50-55% fidelity. Either I'm missing something or there is a bug in the C3 code. In any case, we could use this example to find out what's wrong. Maybe someone can point out if or why the optimisation cannot work like this.~~
It is working now using cross-resonance. The final fidelity is about 99%.

## How
Similar to the existing two qubit example, but with a CNOT gate. ~~I tried the same with other SU(4) gates (SWAP, iSWAP, ...) and with LBFGS instead of CMAES, but none of those converged to a good fidelity.~~

## Checklist

- [ ] Tests - Added unit tests for new code, regression tests for bugs and updated the integration tests if required
- [x] Formatting & Linting - `black` and `flake8` have been used to ensure styling guidelines are met
- [ ] Type Annotations - All new code has been type annotated in the function signatures using type hints
- [ ] Docstrings - Docstrings have been provided for functions in the `numpydoc` style
- [ ] Documentation - The tutorial style documentation has been updated to explain changes & new features
- [x] Notebooks - Example notebooks have been updated to incorporate changes and new features
- [x] Changelog - A short note on this PR has been added to the Upcoming Release section

### CODE REVIEW

**Comment by lazyoracle** [comment]
The tests break because Tensorflow 2.7 drops support for Python 3.6.x (which is fair I guess). I am not sure if that means we drop support for Tensorflow greater than 2.6.x or we drop support for Python less than 3.7.x (I prefer the latter).

**Comment by lazyoracle** [comment]
@alex-simm Can you rebase on `dev`? Hopefully all tests should pass and this PR would be ready for merge.

**Comment by alex-simm** [comment]
> @alex-simm Can you rebase on `dev`? Hopefully all tests should pass and this PR would be ready for merge.

done

**Review by lazyoracle — APPROVED** [review]

**Review by lazyoracle — CHANGES_REQUESTED** [review]
**[UPDATE]** - This is now resolved.

The notebooks are run in the CI as a sort of integration test to ensure code changes don't break examples and they are always up to date. A high number of iterations can cause the CI to run for very long durations thus bottlenecking development. Can you update the number of function evaluations to something like 100 (instead of 1000) with a comment to increase the evaluations for better results?

```python
# increase maxfevals to 500+ for better results
opt = OptimalControl(
    dir_path=log_dir,
    fid_func=fidelities.average_infid_set,
    fid_subspace=["Q1", "Q2"],
    pmap=parameter_map,
    algorithm=algorithms.cmaes,
    options={
        "popsize": 15,
        "maxfevals": 100
    },
    run_name="cnot12"
)
```

**Comment by lazyoracle** [comment]
@alex-simm Is this ready to merge from your end?

**Comment by alex-simm** [comment]
> @alex-simm Is this ready to merge from your end?

Yes it is. I guess the remaining items on the checklist don't apply here

**Pull request merged**
